# Generated by Django 3.2.4 on 2021-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
            preserve_default=False,
        ),
    ]
