# Generated by Django 3.2.4 on 2021-06-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='V. Unitário'),
        ),
    ]
