# Generated by Django 3.2.4 on 2021-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='un',
            field=models.CharField(default='', max_length=5, verbose_name='UN'),
        ),
    ]
