# Generated by Django 3.2.4 on 2021-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_forncedor', models.CharField(choices=[('FISICA', 'FISICA'), ('JURIDICA', 'JURIDICA')], max_length=11, verbose_name='Tipor de Fornecedore')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CNPJ/CPF')),
                ('ie_forncedor', models.CharField(max_length=20, verbose_name='Incrição Estadual/RG')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('UF', models.CharField(max_length=2, verbose_name='UF')),
                ('observações', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
