# Generated by Django 3.2.4 on 2021-06-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0002_fornecedores_telefone'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=50, verbose_name='Modalidade')),
                ('n_contrato', models.CharField(max_length=50, verbose_name='Nº Contrato')),
                ('data', models.DateField(verbose_name='Data')),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('tipo_forn', models.CharField(max_length=50, verbose_name='Tipo Fornecimento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fornecedores.fornecedores', verbose_name='Fornecedor')),
                ('produto', models.ManyToManyField(related_name='contratos', to='produtos.Produtos', verbose_name='Produto')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'ordering': ['modalidade'],
            },
        ),
    ]
